apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-annotations-llgt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-cblq-tenant/build-suite-test-application-crtd/test-annotations-llgt@sha256:c3eece28e52cb46757bf1b4c917adb7d33afb902c8e10e997852fdd9eeca2270
        name: my-nginx
        resources: {}
status: {}
